<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/NINVFUS/ENU/">
    <link rel="canonical" href="http://help.autodesk.com/cloudhelp/ENU/Fusion-360-API/files/EqualDistanceChamferFeature_Sample.htm">
    <meta name="product" content="NINVFUS">
    <meta name="release" content="NA">
    <meta name="book" content="Developer">
    <meta name="component" content="Fusion-360-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="description" content="Equal Distance Chamfer Feature Sample">
    <meta name="topicid" content="GUID-eb68d680-fd07-11e4-8afb-3417ebd3d5be">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Equal Distance Chamfer Feature</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body>
    <link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Equal Distance Chamfer Feature API Sample
        </h1>
    <h2 class="api">
          Description
        </h2>Creates an equal distance chamfer on the selected edge. If there are tangent contiguous edges that will also be included in the chamfer.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#Python">Python</a></li>
        <li><a href="#C++">C++</a></li>
      </ul>
      <div id="Python" class="api-code">
        <pre class="api-code">import adsk.core, adsk.fusion, traceback

def run(context):
    ui = None
    try:
        <span style="color:blue"># Get the Application object.</span>
        app = adsk.core.Application.get()
        
        <span style="color:blue"># Get various top-level objects.</span>
        ui  = app.userInterface
        design = app.activeProduct
        root = design.rootComponent
        
        <span style="color:blue"># Have the edge selected and add it to an ObjectCollection.        </span>
        selection = ui.selectEntity("Select edge to chamfer", "Edges")
        edge = selection.entity
        edgeCollection = adsk.core.ObjectCollection.create()
        edgeCollection.add(edge)
        
        <span style="color:blue"># Create the ChamferInput object.</span>
        chamfers = root.features.chamferFeatures
        chamferInput = chamfers.createInput(edgeCollection, True)      
        chamferInput.setToEqualDistance(adsk.core.ValueInput.createByReal(1))
        
        <span style="color:blue"># Create the chamfer.</span>
        chamfer = chamfers.add(chamferInput)
    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))</pre>
      </div>
      <div id="C++" class="api-code">
        <pre class="api-code">#include &lt;Core/Application/Application.h&gt;
#include &lt;Core/UserInterface/UserInterface.h&gt;
#include &lt;Core/UserInterface/Selection.h&gt;
#include &lt;Core/Application/ObjectCollection.h&gt;
#include &lt;Core/Application/ValueInput.h&gt;

#include &lt;Fusion/Fusion/Design.h&gt;
#include &lt;Fusion/Components/Component.h&gt;
#include &lt;Fusion/BRep/BRepEdge.h&gt;
#include &lt;Fusion/Features/Features.h&gt;
#include &lt;Fusion/Features/ChamferFeatures.h&gt;
#include &lt;Fusion/Features/ChamferFeatureInput.h&gt;

using namespace adsk::core;
using namespace adsk::fusion;

Ptr&lt;UserInterface&gt; ui;

extern "C" XI_EXPORT bool run(const char* context)
{
	Ptr&lt;Application&gt; app = Application::get();
	if (!app)
		return false;

	ui = app-&gt;userInterface();
	if (!ui)
		return false;

	Ptr&lt;Design&gt; design = app-&gt;activeProduct();
	if (!design)
		return false;

	<span style="color:blue">// Get the root component of the active design</span>
	Ptr&lt;Component&gt; root = design-&gt;rootComponent();
	if (!root)
		return false;

	<span style="color:blue">// Have the edge selected and add it to an ObjectCollection.</span>
	Ptr&lt;Selection&gt; selection = ui-&gt;selectEntity("Select edge to chamfer", "Edges");
	if (!selection)
		return false;

	Ptr&lt;BRepEdge&gt; edge = selection-&gt;entity();
	if (!edge)
		return false;

	Ptr&lt;ObjectCollection&gt; edgeCollection = ObjectCollection::create();
	if (!edgeCollection)
		return false;
	edgeCollection-&gt;add(edge);

	Ptr&lt;Features&gt; feats = root-&gt;features();
	if (!feats)
		return false;

	Ptr&lt;ChamferFeatures&gt; chamfers = feats-&gt;chamferFeatures();
	if (!chamfers)
		return false;

	Ptr&lt;ChamferFeatureInput&gt; chamferInput = chamfers-&gt;createInput(edgeCollection, true);
	if (!chamferInput)
		return false;
	chamferInput-&gt;setToEqualDistance(ValueInput::createByReal(1.0));

	Ptr&lt;ChamferFeature&gt; chamfer = chamfers-&gt;add(chamferInput);
	return true;
}


#ifdef XI_WIN

#include &lt;windows.h&gt;

BOOL APIENTRY DllMain(HMODULE hmodule, DWORD reason, LPVOID reserved)
{
	switch (reason)
	{
	case DLL_PROCESS_ATTACH:
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

#endif <span style="color:blue">// XI_WIN</span></pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2017 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com&subject=Fusion%20December 2017%20API%20Help%20(EqualDistanceChamferFeature%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>